version: '3.8'

services:
  stats-server:
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=testdb

  stats-db:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_DB=stats
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  ewm-service:
    ports:
      - "8082:8082"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=testdb

  ewm-db:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_DB=main
    volumes:
      - ewm-db-data:/var/lib/postgresql/data

volumes:
  stats-db-data:
  ewm-db-data:
